backend ="glx";
vsync = true;
use-damage = true;
corner-radius = 16;
use-ewmh-active-win = true;

blur:
{
  method = "dual_kawase";
  strength = 5;
  size = 3;
};

rules = (
	{
		match = "fullscreen";
		corner-radius = 0;
	},

	{
		match = "class_g = 'steam'"
		corner-radius = 0; 
	},

	{
		match = "class_g != 'Alacritty'";
		blur-background = false;
	},

	{ 
		match = "class_g != 'flameshot' && class_g != 'Dunst'"
		animations = (
			{
				triggers = ["geometry"];
//				preset = "geometry-change";
//				duration = 0.25;		
			
				scale-x = {
					curve = "cubic-bezier(0.6, 1.3, 0.8, 1)"
					duration = 0.25
					start = "window-width-before / window-width"
					end = 1
				
				}
				scale-y = {
					curve = "cubic-bezier(0.6, 1.3, 0.8, 1)"
					duration = 0.25
					start = "window-height-before / window-height"
					end = 1
				
				}
				offset-x = {
					curve = "cubic-bezier(0.6, 1.3, 0.8, 1)"
					duration = 0.25
					start = "window-x-before - window-x"
					end = 0
				}
				offset-y = {
					curve = "cubic-bezier(0.6, 1.3, 0.8, 1)"
					duration = 0.25
					start = "window-y-before - window-y"
					end = 0
				}
				
			},
			{
				triggers = ["open"];
//			preset = "appear";
//			duration = 0.26;
				opacity = {
					curve = "cubic-bezier(0, 0.5, 1, 1)"
					duration = 0.2
					start = 0.6
					end = 1
				}
				scale-x = {
					curve = "cubic-bezier(0.0, 1.0, 1.0, 1.0)"
					duration = 0.2
					start = 0.8
					end = 1
				}
				scale-y = {
					curve = "cubic-bezier(0.0, 1.0, 1.0, 1.0)"
					duration = 0.2
					start = 0.8
					end = 1
				}
		
				offset-x = {
					curve = "cubic-bezier(0.0, 1.0, 1.0, 1.0)"
					duration = 0.2
					start = "window-width / 10 "
					end = 0
				}
				offset-y = {
					curve = "cubic-bezier(0.0, 1.0, 1.0, 1.0)"
					duration = 0.2
					start = "window-height / 10"
					end = 0
				}		
		
			},
			{
				triggers = ["close"];
//		preset = "disappear";
//		duration = 0.15;


				scale-x = {
					curve = "cubic-bezier(0,1,1,1)"
					duration = 0.25
					start = 1
					end = 0.8
				}
				scale-y = {
					curve = "cubic-bezier(0,1,1,1)"
					duration = 0.25
					start = 1
					end = 0.8
				}
				offset-x = {
					curve = "cubic-bezier(0,1,1,1)"
					duration = 0.25
					start = 0
					end = "window-width / 10 "
				}
				offset-y = {
					curve = "cubic-bezier(0,1,1,1)"
					duration = 0.25
					start = 0
					end = "window-height / 10 "
				}

		
				opacity = {
					curve = "cubic-bezier(0, 0.5, 1, 1)"
					duration = 0.15
					start = 0.8
					end = 0
				}
			
			},
		)
	}
)

fading = true;
fade-in-step = 0.1;
fade-out-step = 0.1;

