#! /bin/sh

	#Настройки X-сессии
setxkbmap -layout us,ru -option -option grp:win_space_toggle

xrdb -merge ~/.Xresources 
xsetroot -cursor_name left_ptr

xrandr --output eDP-1 --primary --auto --output HDMI-1 --left-of eDP-1 --auto
#xrandr --output eDP-1 --primary --auto --output HDMI-1 --right-of eDP-1 --auto

xinput set-prop "SYNA3602:00 0911:5288 Touchpad" "libinput Natural Scrolling Enabled" 1
xinput set-prop "SYNA3602:00 0911:5288 Touchpad" "libinput Scrolling Pixel Distance" 35
xinput set-prop "SYNA3602:00 0911:5288 Touchpad" "libinput Tapping Enabled" 1

xinput set-prop "YJX-CHIP MCHOSE G7 Mouse" "libinput Natural Scrolling Enabled" 0
xinput set-prop "YJX-CHIP MCHOSE G7 Mouse" "libinput Accel Profile Enabled" 0, 1

	#Автозапуск
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -f xdg-desktop-portal > /dev/null || /usr/libexec/xdg-desktop-portal &
pgrep -f polkit-mate-authentication-agent-1 > /dev/null || /usr/libexec/polkit-mate-authentication-agent-1 &
pgrep -x picom > /dev/null || picom --config ~/.config/picom/picom.conf -b
#pgrep -x feh >  /dev/null || feh -z --bg-fill Изображения/wallpapers &
pgrep -x polybar > /dev/null || polybar main &
pgrep -x dunst > /dev/null || dunst &
pgrep -x flameshot > /dev/null || flameshot &
pgrep -x xfce4-power-manager > /dev/null || xfce4-power-manager &
pgrep -x tg-ws-proxy > /dev/null || tg-ws-proxy &

nitrogen --restore &


#pgrep -x > /dev/null

	#Настройки bspwm
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor HDMI-1 -d I

bspc config border_width         2
bspc config normal_border_color	 ''
bspc config focused_border_color '#d08770'
bspc config window_gap           8

bspc config split_ratio          	0.5
#bspc config borderless_monocle   	true
#bspc config gapless_monocle      	true
bspc config single_monocle       	true
bspc config focus_follows_pointer	true

bspc rule -a pavucontrol state=floating  
bspc rule -a feh state=floating 
bspc rule -a Qalculate state=floating
bspc rule -a AmneziaVPN state=floating
bspc rule -a org-springframework-boot-loader-PropertiesLauncher state=floating
bspc rule -a Throne state=floating center=on
bspc rule -a Onboard state=floating rectangle=800*600
bspc rule -a Nitrogen state=floating center=on
