[colors]
;background = #080f19
background = #1f2531
background-alt = #353942
;main = #334f7d
main = #d08770
text = #d8dee9
;text = #C5C5C6

;NEW COLORS
red     = #bf616a
green   = #a3be8c
yellow  = #ebcb8b
blue    = #81a1c1
magenta = #b48ead
cyan    = #8fbcbb
white   = #eceff4


[bar/main]
monitor = eDP-1

width = 1848
height = 32
offset-x = 36
offset-y = 4
;fixed-center = true 
padding-left = 1
padding-right = 1
module-margin = 8px
padding = 1
;enable-ipc = true
;override-redirect = true
wm-restack = bspwm
;separator = \
separator-foreground = ${colors.background-alt} 

background = ${colors.background}
;foreground = 

radius = 8
line-size = 3pt

font-0 = Symbols Nerd Font:size=14;3
font-1 = JetBrainsMono Nerd Font:size=14;3

modules-left = logo xworkspaces   
modules-center = date
modules-right = battery pulseaudio backlight xkeyboard  wlan power-menu tray

;modules-left = tray xworkspaces xwindow
;modules-center =  temperature cpu memory filesystem
;modules-right = xkeyboard battery pulseaudio backlight wlan date power-menu

[bar/second]
monitor = HDMI-1
offset-x = 8
offset-y = 4

height = 24pt
width = 1584
padding-left = 1
padding-right = 1
module-margin = 1
wm-restack = bspwm
separator-foreground = ${colors.background-alt} 

bottom = true

background = ${colors.background}
line-size = 3pt

font-0 = Symbols Nerd Font:size=14;2
font-1 = Symblos Nerd Font Mono:size=14;2

modules-left = logo xworkspaces   
modules-center = xwindow
modules-right = battery pulseaudio backlight xkeyboard date wlan power-menu

[module/dunst]
type = custom/script
interval = 1
exec = if dunstctl is-paused | grep -q "true"; then echo "󰂛"; else echo "󰂚"; fi
click-left = dunstctl set-paused toggle
format-foreground = ${colors.cyan}

[module/tray]
type = internal/tray
tray-spacing = 4px
;tray-size = 60%
tray-foreground = ${colors.main}

[module/logo]
type = custom/text
format = <label>
format-foreground = ${colors.red}
label = 
click-right = alacritty --hold -e fastfetch

[module/cpu]
type = internal/cpu
interval = 0.5
warn-percentage = 90

format =  <label>
format-foreground = ${colors.main}
format-warn =  <label-warn>
format-warn-foreground = ${colors.main}

label = %percentage%%
label-foreground = ${colors.text}
label-warn = %percentage%%
label-warn-foreground = ${colors.text}

[module/memory]
type = internal/memory
interval = 3

format =  <label>
format-foreground = ${colors.main}
label = %gb_used%
label-foreground =  ${colors.text}

[module/xworkspaces]
type = internal/xworkspaces
pin-workspaces = true

label-active = %name%
;label-active-background = ${colors.main}
label-active-foreground = ${colors.main}

label-active-underline = ${colors.main}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-empty = %name%
label-empty-foreground = #55
label-empty-padding = 1

[module/battery]
type = internal/battery
low-at = 5
battery = BAT0
adapter = ADP1
poll-interval = 5

format-low =  !<label-low>
format-low-foreground = ${colors.red}
label-low = %percentage%%
label-low-foreground = ${colors.text}

format-full =  <label-full>
format-full-foreground = ${colors.green}
label-full = %percentage%%
label-full-foreground = ${colors.text}

format-charging = 󱐋 <label-charging>
format-charging-foreground = ${colors.green}
label-charging = %percentage%%
label-charging-foreground = ${colors.text}

format-discharging = <ramp-capacity> <label-discharging>
format-discharging-foreground = ${colors.yellow}
label-discharging = %percentage%%
label-discharging-foreground = ${colors.text}

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

[module/pulseaudio]
type = internal/pulseaudio
use-ui-max = true

;format-volume = <ramp-volume> <bar-volume> <label-volume>
format-volume = <ramp-volume> <label-volume>

format-volume-foreground = ${colors.blue}
label-volume = %percentage%%
label-volume-foreground = ${colors.text}

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 

bar-volume-width = 7
bar-volume-indicator = 
bar-volume-fill = 
bar-volume-empty = 
;  

label-muted = 󰝟 
label-muted-foreground = ${colors.background-alt}

click-right = pavucontrol

[module/backlight]
type = internal/backlight
poll-interval = 0
enable-scroll = true
scroll-interval = 10

;format = <ramp> <bar> <label>
format = <ramp> <label>
format-foreground = ${colors.magenta}

ramp-0 = 
ramp-1 = 󰪞
ramp-2 = 󰪟
ramp-3 = 󰪠
ramp-4 = 󰪡
ramp-5 = 󰪢
ramp-6 = 󰪣
ramp-7 = 󰪤
ramp-8 = 󰪥

;ramp-0 = 󱩎
;ramp-1 = 󱩐
;ramp-2 = 󱩒
;amp-3 = 󱩔
;ramp-4 = 󰛨
;   

bar-width = 7
bar-indicator = 
bar-fill = 
bar-empty = 

label = %percentage%%
label-foreground = ${colors.text}

[module/date]
type = internal/date
interval = 1

date = %H:%M
date-alt = %Y-%m-%d %H:%M:%S
format = 󰥔 <label>
;format =  <label>

format-foreground = ${colors.cyan}
;format-background = ${colors.background-alt}
label =  %date%
label-foreground = ${colors.text}

[network-base]
type = internal/network
interval = 5
format-connected = 󰖩 
;<label-connected>
format-connected-foreground = ${colors.green}
click-right = pavucontrol

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %essid%(%signal%%)
label-connected-foreground = ${colors.text}
label-disconnected =  
label-disconnected-foreground = ${colors.background-alt}


[module/temperature]
type = internal/temperature
thermal-zone = 5

format =  <label>
format-foreground =  ${colors.main}
label = %temperature-c%
label-foreground = ${colors.text}

format-warn = 󰈸 <label-warn>
format-warn-foreground = ${colors.main}
label-warn = %temperature-c%
label-warn-foreground = ${colors.text}

[module/xkeyboard]
type = internal/xkeyboard

blacklist-0 = num lock
blacklist-1 = scroll lock
blacklist-2 = caps lock
;;;;;󰌌 󰗊  
;format-label-layout =   <label-layout>
;format-label-layout-foreground = ${colors.main}
format-prefix = 󰗊
format-prefix-foreground = ${colors.main}

label-layout = %layout%
;label-layout-padding = 
label-layout-foreground = ${colors.text}

[module/xwindow]
type = internal/xwindow
format = <label>
label = %class%
label-maxlen = 50

[module/filesystem]
type = internal/fs

mount-0 = /

format-mounted =  <label-mounted>
format-mounted-foreground = ${colors.main}
label-mounted = %used%/%total%
label-mounted-foreground = ${colors.text}

[module/power-menu]
type = custom/text
label = "⏻"
label-foreground = ${colors.red}
click-left = power.sh
